version: '3'

services:
  redmine:
    image: redmine:3.3-passenger
    restart: always
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: passwd
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/redmine/files:/usr/src/redmine/files
      - ./docker/redmine/plugins:/usr/src/redmine/plugins
      - ./docker/redmine/themes:/usr/src/redmine/public/themes
    ports:
      - 17300:3000
    links:
      - postgres

  postgres:
    image: postgres:12.1
    restart: always
    environment:
      REDMINE_DB_DATABASE: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: passwd
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
